### ISSUE TITLE
dont see video on my channel

### ISSUE THREAD

**Issue by TrojansSuck** [theabbie/Youtube-Uploader-Bot#10]
whenever i run the script i dont see no video on my channel

**Comment by theabbie** [comment]
@TrojansSuck Visit YouTube Studio, video must have been uploaded but was locked as YouTube doesn't allow public videos from unverified bots, no solution for that, need to get bot verified by YouTube which is pretty tough.

**Comment by TrojansSuck** [comment]
thanks for response, ill try that later :D
