### ISSUE TITLE
Private (locked)

### ISSUE THREAD

**Issue by number0x0001** [theabbie/Youtube-Uploader-Bot#13]
Hello! Thank you for the excellent tutorial - I was able to set this up easily and quickly. The problem I am running into is that Youtube privates the video as soon as I upload it. I saw somewhere that this is because the app/script is unverified? I'm not interested in taking the time to try to get it verified, so is there a way around this block or is there an already verified script that can be used for this purpose?

**Comment by theabbie** [comment]
@itsabham getting verified is the only solution, if you don't wanna do it yourself you'll need to find someone who has it verified already, but youtube limits the number of uploads per day, so, I don't think anyone will allow using their script for free.

**Comment by number0x0001** [comment]
Interesting, thanks for the insight.
