### ISSUE TITLE
Website for MP$

### ISSUE THREAD

**Issue by hsingh132** [theabbie/Youtube-Uploader-Bot#16]
Hey! 
Would you be able to drop me a free software I could use to convert the MP4 into like a raw link? Cant seem to find any. Thanks!

**Comment by theabbie** [comment]
@hsingh132 There isn't any software, you need to find a website which allows uploading, https://ezgif.com can be used, use any video tool and upload video, and copy the link of mp4 download.

**Comment by hsingh132** [comment]
Alright thanks a bunch, for the product in general and your response.

**Comment by hsingh132** [comment]
Hi, so my video is around 45 seconds, and the site you reccomeneded only allows 5 fps for that length of time. Would you happen to know which other sites? Becasue I cant seem to find any with a google search. @theabbie Sorry to reopen

**Comment by theabbie** [comment]
@hsingh132 Maybe imgur.com and after uploading, inspect element on video and get the `src` attribute of the video.

**Comment by hsingh132** [comment]
alright, I will try that right now
Thanks again

**Comment by hsingh132** [comment]
Thank you so much this worked!!!
